param(
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")),
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$docsRoot = Join-Path $RepositoryRoot "docs"
$manifestPath = Join-Path $docsRoot "document-status.csv"
$outputPath = Join-Path $docsRoot "DOCUMENT_STATUS.md"
$allowedStatuses = @("current", "completed", "historical", "deferred", "superseded")
$roadmapPattern = '(?i)(roadmap|implementation[_ -]?plan|test[_ -]?plan|migration[_ -]?plan|todo)\.md$'

$manifest = @(Import-Csv -LiteralPath $manifestPath)
$manifestByPath = @{}
foreach ($entry in $manifest) {
    $path = $entry.path.Replace('\', '/')
    if ($manifestByPath.ContainsKey($path)) {
        throw "Duplicate document-status entry: $path"
    }
    if ($allowedStatuses -notcontains $entry.status) {
        throw "Unsupported status '$($entry.status)' for $path"
    }
    if (-not (Test-Path -LiteralPath (Join-Path $RepositoryRoot $path))) {
        throw "Document-status entry points to a missing file: $path"
    }
    $manifestByPath[$path] = $entry
}

$discovered = @(Get-ChildItem -LiteralPath $docsRoot -Recurse -File -Filter "*.md" |
    ForEach-Object { $_.FullName.Substring($RepositoryRoot.Length + 1).Replace('\', '/') } |
    Where-Object { $_ -match $roadmapPattern } |
    Sort-Object)

$missing = @($discovered | Where-Object { -not $manifestByPath.ContainsKey($_) })
$extra = @($manifestByPath.Keys | Where-Object { $discovered -notcontains $_ } | Sort-Object)
if ($missing.Count -gt 0 -or $extra.Count -gt 0) {
    $details = @()
    if ($missing.Count -gt 0) { $details += "Unclassified roadmap documents: $($missing -join ', ')" }
    if ($extra.Count -gt 0) { $details += "Manifest entries outside roadmap discovery: $($extra -join ', ')" }
    throw ($details -join [Environment]::NewLine)
}

$lines = @(
    "# Document Status",
    "",
    "Generated by ``tools/scripts/generate-document-status.ps1`` from ``docs/document-status.csv``.",
    "Do not edit this file directly. The generator treats files whose names end in roadmap, implementation plan, test plan, migration plan, or TODO as roadmap documents and fails when any is unclassified.",
    "",
    "Status meanings:",
    "",
    "- **CURRENT**: authoritative active guidance.",
    "- **COMPLETED**: acceptance scope was delivered; retained as evidence.",
    "- **HISTORICAL**: useful implementation history but not current guidance.",
    "- **DEFERRED**: deliberately postponed behind an explicit gate.",
    "- **SUPERSEDED**: replaced by the linked current document.",
    "",
    "Roadmap documents indexed: **$($manifest.Count)**.",
    ""
)

foreach ($status in $allowedStatuses) {
    $entries = @($manifest | Where-Object { $_.status -eq $status } | Sort-Object path)
    $lines += "## $($status.ToUpperInvariant()) ($($entries.Count))"
    $lines += ""
    $lines += "| Document | Replacement / authority | Reason |"
    $lines += "|---|---|---|"
    foreach ($entry in $entries) {
        $link = "[$($entry.path)]($($entry.path.Substring(5)))"
        $replacement = if ([string]::IsNullOrWhiteSpace($entry.replacement)) {
            "--"
        } else {
            "[$($entry.replacement)]($($entry.replacement.Substring(5)))"
        }
        $lines += "| $link | $replacement | $($entry.reason) |"
    }
    $lines += ""
}

$content = ($lines -join "`n").TrimEnd() + "`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $outputPath)) {
        throw "Generated document-status index is missing: $outputPath"
    }
    $existing = Get-Content -LiteralPath $outputPath -Raw
    if ($existing.Replace("`r`n", "`n") -ne $content) {
        throw "DOCUMENT_STATUS.md is stale. Run tools/scripts/generate-document-status.ps1."
    }
    return
}

Set-Content -LiteralPath $outputPath -Value $content -Encoding utf8 -NoNewline
