const pages=["overview","items","transactions","agents","market","decisions","validation"];
let db=null,cutoff=null;
const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const n=v=>Number(v||0), fmt=v=>new Intl.NumberFormat().format(n(v)), date=v=>String(v||"").slice(0,10), itemName=id=>`${db?.itemNames?.[id]||"Unknown item"} · ${id}`;
const filtered=rows=>!cutoff?rows:(rows||[]).filter(r=>date(r.logical_date||r.logical_at||r.logical_time||r.opened_at||r.started_at)<=cutoff);
const asArray=value=>Array.isArray(value)?value:(value&&Object.keys(value).length?[value]:[]);
const json=v=>{try{return typeof v==="string"?JSON.parse(v):v||{}}catch{return {raw:v}}};
function panel(title,body,cls="full"){return `<article class="panel card ${cls}"><h2>${esc(title)}</h2>${body}</article>`}
function metric(label,value,tone=""){return `<article class="panel card metric quarter"><span>${esc(label)}</span><strong class="${tone}">${esc(value)}</strong></article>`}
function table(rows,columns){if(!rows?.length)return $("empty").innerHTML;return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>`<th>${esc(c[0])}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${columns.map(c=>`<td class="${c[2]||""}">${c[1](r)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
function lineChart(series){const all=series.flatMap(s=>s.points.map(p=>p[1]));if(!all.length)return $("empty").innerHTML;const W=800,H=230,p=32,max=Math.max(...all,1),count=Math.max(...series.map(s=>s.points.length),2);let svg=`<svg viewBox="0 0 ${W} ${H}">`;for(let i=0;i<5;i++){let y=p+(H-2*p)*i/4;svg+=`<line class="gridline" x1="${p}" x2="${W-p}" y1="${y}" y2="${y}"/><text class="axis" x="2" y="${y+4}">${fmt(max*(4-i)/4)}</text>`}series.forEach((s,si)=>{const pts=s.points.map((v,i)=>`${p+i*(W-2*p)/(count-1)},${H-p-v[1]*(H-2*p)/max}`).join(" ");svg+=`<polyline class="series ${si?"secondary":""}" points="${pts}"/>`});return svg+`</svg><p class="muted">${series.map((s,i)=>`<span style="color:${i?"var(--gold)":"var(--mint)"}">●</span> ${esc(s.name)}`).join(" &nbsp; ")}</p>`}
function bars(rows,label,value){if(!rows.length)return $("empty").innerHTML;const top=rows.slice(0,14),max=Math.max(...top.map(value),1);return `<svg viewBox="0 0 800 250">${top.map((r,i)=>{const y=8+i*17,w=value(r)/max*570;return `<text class="axis" x="0" y="${y+10}">${esc(label(r)).slice(0,27)}</text><rect class="bar" x="175" y="${y}" width="${w}" height="11"/><text class="axis" x="${185+w}" y="${y+10}">${fmt(value(r))}</text>`}).join("")}</svg>`}
function renderOverview(){const s=db.summary||{},flows=filtered(db.mesoDaily||[]),byDate={};flows.forEach(r=>{let x=byDate[r.logical_date]??={source:0,sink:0};const k=/SINK|BURN|TAX|SPEND|NPC_PURCHASE/i.test(r.flow_kind)?"sink":"source";x[k]+=Math.abs(n(r.meso_amount))});const series=Object.entries(byDate).map(([d,v])=>({d,...v}));const kinds=(db.eventKinds||[]);$("overview").innerHTML=[metric("Admitted agents",fmt(s.admitted_agents)),metric("Agent meso supply",fmt(s.agent_mesos)),metric("Economic transactions",fmt(s.transactions)),metric("Open invariants",fmt(s.open_violations),n(s.open_violations)?"bad":"ok"),panel("Meso sources and sinks",lineChart([{name:"Sources",points:series.map((v,i)=>[i,v.source])},{name:"Sinks",points:series.map((v,i)=>[i,v.sink])}]),"half chart"),panel("Economic event mix",bars(kinds,r=>r.event_kind,r=>n(r.event_count)),"half chart"),panel("Run facts",table([db.run],[["Scenario",r=>esc(r.scenario_id)],["Status",r=>`<span class="pill">${esc(r.status)}</span>`],["Logical time",r=>esc(r.logical_current_at)],["Target",r=>esc(r.target_logical_at)],["Seed",r=>esc(r.seed)],["Failure",r=>esc(r.failure_reason||"—"),"wrap"]]),"full")].join("")}
function itemIds(){return [...new Set([...(db.itemDaily||[]).map(r=>r.item_id),...(db.lots||[]).map(r=>r.item_id),...(db.transactions||[]).map(r=>r.item_id),...(db.listings||[]).map(r=>r.item_id)].filter(Boolean))].sort((a,b)=>n(a)-n(b))}
function renderItems(){const ids=itemIds();const prior=$("itemSelect")?.value||ids[0]||"";const selected=ids.includes(prior)?prior:ids[0];const daily=filtered(db.itemDaily||[]).filter(r=>String(r.item_id)===String(selected));const tx=filtered(db.transactions||[]).filter(r=>String(r.item_id)===String(selected));const lots=(db.lots||[]).filter(r=>String(r.item_id)===String(selected));const decisions=filtered(db.decisions||[]).filter(r=>JSON.stringify(r).includes(`\"itemId\": ${selected}`)||JSON.stringify(r).includes(`\"itemId\":${selected}`));$("items").innerHTML=panel("Item explorer",`<div class="toolbar"><select id="itemSelect">${ids.map(id=>`<option value="${id}" ${String(id)===String(selected)?"selected":""}>${esc(itemName(id))}</option>`).join("")}</select></div><div class="split"><div><h3>Price and volume</h3>${lineChart([{name:"VWAP",points:daily.map((r,i)=>[i,n(r.vwap)])},{name:"Quantity",points:daily.map((r,i)=>[i,n(r.completed_quantity)])}])}</div><div><h3>Introduction and destruction</h3>${lineChart([{name:"Farm + quest + NPC created",points:daily.map((r,i)=>[i,n(r.farm_created_quantity)+n(r.quest_created_quantity)+n(r.npc_created_quantity)])},{name:"Consumed + NPC destroyed",points:daily.map((r,i)=>[i,n(r.consumed_quantity)+n(r.npc_destroyed_quantity)])}])}</div></div>`,"full")+panel(`Transactions · ${itemName(selected)}`,table(tx,[["Time",r=>esc(r.logical_at)],["Kind",r=>esc(r.transaction_kind)],["Buyer",r=>esc(r.buyer_id||"—")],["Seller",r=>esc(r.seller_id||"—")],["Qty",r=>fmt(r.quantity)],["Gross",r=>fmt(r.gross_mesos)],["Tax",r=>fmt(r.tax_mesos)]]),"half")+panel("Provenance lots",table(lots,[["Lot",r=>esc(r.lot_id)],["Source",r=>esc(r.source_kind)],["Identifier",r=>esc(r.source_identifier)],["Original qty",r=>fmt(r.original_quantity)],["Attributes",r=>esc(r.attributes),"wrap"]]),"half")+panel("Decisions mentioning this item",table(decisions,[["Time",r=>esc(r.logical_time)],["Agent",r=>esc(r.agent_id)],["Decision",r=>esc(r.decision_kind)],["Chosen action",r=>esc(r.chosen_action),"wrap"]]),"full");$("itemSelect")?.addEventListener("change",renderItems)}
function searchablePage(id,title,rows,cols){$(id).innerHTML=panel(title,`<div class="toolbar"><input id="${id}Search" placeholder="Filter all fields"></div><div id="${id}Table">${table(rows,cols)}</div>`,"full");$(`${id}Search`).addEventListener("input",e=>{$(`${id}Table`).innerHTML=table(rows.filter(r=>JSON.stringify(r).toLowerCase().includes(e.target.value.toLowerCase())),cols)})}
function renderTransactions(){searchablePage("transactions","Completed economic transactions",filtered(db.transactions||[]),[["Time",r=>esc(r.logical_at)],["Kind",r=>esc(r.transaction_kind)],["Item",r=>r.item_id?esc(itemName(r.item_id)):"—"],["Qty",r=>fmt(r.quantity)],["Gross",r=>fmt(r.gross_mesos)],["Tax",r=>fmt(r.tax_mesos)],["Buyer",r=>esc(r.buyer_id||"—")],["Seller",r=>esc(r.seller_id||"—")],["Evidence",r=>esc(r.evidence),"wrap"]])}
function renderAgents(){const rows=(db.agents||[]).slice().sort((a,b)=>n(b.meso)-n(a.meso));$("agents").innerHTML=panel("Wealth distribution",bars(rows,r=>r.agent_id,r=>n(r.meso)),"half chart")+panel("Current states",table(rows,[["Agent",r=>esc(r.agent_id)],["Level",r=>fmt(r.level)],["EXP",r=>fmt(r.experience)],["Mesos",r=>fmt(r.meso)],["Map",r=>esc(r.map_id)],["State",r=>esc(r.activity_state)],["Needs",r=>esc(r.needs),"wrap"]]),"half")}
function renderMarket(){const traffic=db.roomTraffic||[],stalls=filtered(db.stalls||[]),listings=filtered(db.listings||[]);$("market").innerHTML=panel("Room traffic",bars(traffic,r=>`Map ${r.map_id}`,r=>n(r.visits)),"half chart")+panel("Physical stalls",table(stalls,[["Opened",r=>esc(r.opened_at)],["Seller",r=>esc(r.seller_id)],["Room",r=>esc(r.room_map_id)],["Spot X",r=>esc(r.spot_x)],["Closed",r=>esc(r.closed_at||"Open")],["Reason",r=>esc(r.close_reason||"—")]]),"half")+panel("Listings and censored exposure",table(listings,[["Opened",r=>esc(r.opened_at)],["Seller",r=>esc(r.seller_id)],["Item",r=>esc(itemName(r.item_id))],["Bundle",r=>`${fmt(r.quantity_per_bundle)} × ${fmt(r.bundles_remaining)}/${fmt(r.bundles_initial)}`],["Ask",r=>fmt(r.bundle_price)],["Reprices",r=>fmt(r.reprices)],["Close reason",r=>esc(r.close_reason||"Open")]]),"full")}
function renderDecisions(){searchablePage("decisions","Decision journal: alternatives, needs, beliefs and reasons",filtered(db.decisions||[]),[["Time",r=>esc(r.logical_time)],["Agent",r=>esc(r.agent_id)],["Kind",r=>esc(r.decision_kind)],["Chosen",r=>esc(r.chosen_action),"wrap"],["Alternatives",r=>esc(r.alternatives),"wrap"],["Needs",r=>esc(r.needs_used),"wrap"],["Utility",r=>esc(r.utility_breakdown),"wrap"]])}
function renderValidation(){const inv=db.invariants||[],fail=db.ingestionFailures||[];$("validation").innerHTML=metric("Open invariant violations",fmt(inv.filter(v=>!v.resolved_at).length),inv.some(v=>!v.resolved_at)?"bad":"ok")+metric("Ingestion failures",fmt(fail.length),fail.length?"bad":"ok")+metric("Recorded run status",db.run.status,/FAILED|VIOLATION/.test(db.run.status)?"bad":"ok")+metric("Catalog revision",String(db.run.catalog_version||"").slice(0,10))+panel("Invariant journal",table(inv,[["Time",r=>esc(r.logical_at)],["Severity",r=>esc(r.severity)],["Code",r=>esc(r.invariant_code)],["Resolved",r=>esc(r.resolved_at||"Open")],["Evidence",r=>esc(r.evidence),"wrap"]]),"half")+panel("Evidence ingestion failures",table(fail,Object.keys(fail[0]||{}).map(k=>[k,r=>esc(r[k]),"wrap"])),"half")+panel("Public trade and negotiation chat",table(filtered(db.social||[]),[["Time",r=>esc(r.logical_time)],["Room",r=>esc(r.room_map_id)],["Speaker",r=>esc(r.speaker_agent_id)],["Kind",r=>esc(r.event_kind)],["Text",r=>esc(r.public_text),"wrap"],["Item",r=>r.related_item_id?esc(itemName(r.related_item_id)):"—"]]),"full")}
function render(){renderOverview();renderItems();renderTransactions();renderAgents();renderMarket();renderDecisions();renderValidation()}
async function load(){try{const response=await fetch($("dataPath").value,{cache:"no-store"});if(!response.ok)throw new Error(`${response.status} ${response.statusText}`);db=await response.json();for(const key of ["mesoDaily","itemDaily","transactions","lots","stalls","listings","observations","decisions","agents","presence","activities","social","negotiations","invariants","ingestionFailures","eventKinds","decisionKinds","roomTraffic"])db[key]=asArray(db[key]);const dates=[db.run.logical_started_at,...db.itemDaily.map(r=>r.logical_date),...db.mesoDaily.map(r=>r.logical_date)].filter(Boolean).map(date).sort();const start=new Date(dates[0]||Date.now()),end=new Date(dates.at(-1)||start),days=Math.max(0,Math.round((end-start)/86400000));$("daySlider").max=days;$("daySlider").value=days;cutoff=dates.at(-1)||null;$("dayLabel").textContent=cutoff?`Through ${cutoff}`:"All evidence";$("runBadge").textContent=`${db.run.status} · ${db.run.run_id.slice(0,8)} · exported ${new Date(db.generatedAt).toLocaleString()}`;render()}catch(e){$("overview").innerHTML=`<div class="error full">Could not load report data: ${esc(e.message)}</div>`}}
pages.forEach((id,i)=>{const b=document.createElement("button");b.textContent=id[0].toUpperCase()+id.slice(1);b.className=i?"":"active";b.onclick=()=>{pages.forEach(p=>$(p).hidden=p!==id);document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b))};$("tabs").appendChild(b)});
$("loadButton").onclick=load;$("daySlider").oninput=e=>{if(!db)return;const start=new Date(date(db.run.logical_started_at));start.setUTCDate(start.getUTCDate()+n(e.target.value));cutoff=start.toISOString().slice(0,10);$("dayLabel").textContent=`Through ${cutoff}`;render()};load();
