package server.agents.economy.market;

public enum EconomicReason {
    NPC_FLOOR_DISPOSITION,
    INVENTORY_PRESSURE,
    LIQUIDITY_NEEDED,
    QUEST_REQUIREMENT,
    EQUIPMENT_UPGRADE,
    CONSUMABLE_RESTOCK,
    AMMUNITION_RESTOCK,
    RECHARGE,
    SCROLL_UPGRADE,
    COMPLEMENTARY_EQUIPMENT,
    SPECULATIVE_RESALE,
    COLLECTIBLE_OR_CHAIR,
    OBSERVED_UNDERPRICING,
    FAILED_TO_SELL,
    NEGOTIATED_AGREEMENT
}
