package config;

/**
 * Agent-engine owned rollout and policy configuration.
 *
 * <p>This model intentionally lives outside {@link ServerConfig}: changing an
 * Agent capability must not expand the Cosmic server/client configuration
 * surface. Capability catalogs and personality profiles remain versioned
 * resources; this file contains deployment-level switches and bounds.</p>
 */
public class AgentEngineConfig {
    public String AGENT_MOB_REACTION_MODE;
    public int AGENT_SYNTHETIC_MOB_KNOCKBACK_DISTANCE_X;
    public int AGENT_SYNTHETIC_MOB_KNOCKBACK_DURATION_MS;
    public int AGENT_SYNTHETIC_MOB_CONTROL_HOLD_MS;
    public int AGENT_MOB_PHYSICS_PUBLICATION_INTERVAL_MS;
    public int AGENT_MOB_PHYSICS_MAX_CATCH_UP_STEPS;
    public int AGENT_MOB_PHYSICS_STOP_DISTANCE_X;
    public int AGENT_MOB_PHYSICS_RESUME_DISTANCE_X;
    public int AGENT_MOB_PHYSICS_FLY_DEAD_ZONE_X;
    public int AGENT_MOB_PHYSICS_FLY_DEAD_ZONE_Y;
    public int AGENT_MOB_PHYSICS_JUMP_COOLDOWN_MS;
    public int AGENT_MOB_PHYSICS_JUMP_COOLDOWN_JITTER_MS;
    public int AGENT_MOB_PHYSICS_JUMP_TARGET_HEIGHT;
    public int AGENT_MOB_PHYSICS_MAX_SAFE_EDGE_PX;
    public int AGENT_MOB_PHYSICS_LEFT_EDGE_INSET_PX;
    public int AGENT_MOB_PHYSICS_RIGHT_EDGE_INSET_PX;
    public int AGENT_MOB_PHYSICS_SPEED_PERCENT;
    public int AGENT_MOB_PHYSICS_BEHAVIOR_JITTER_MS;
    public int AGENT_MOB_PHYSICS_DIRECTION_REACTION_MAX_MS;
    public int AGENT_MOB_PHYSICS_EDGE_RETREAT_CHANCE_PERCENT;
    public int AGENT_MOB_PHYSICS_EDGE_IDLE_MIN_MS;
    public int AGENT_MOB_PHYSICS_EDGE_IDLE_MAX_MS;
    public int AGENT_MOB_PHYSICS_EDGE_RETREAT_MIN_MS;
    public int AGENT_MOB_PHYSICS_EDGE_RETREAT_MAX_MS;
    public int AGENT_MOB_PHYSICS_RETREAT_MIN_DISTANCE_PX;
    public int AGENT_MOB_PHYSICS_RETREAT_MAX_DISTANCE_PX;
    public int AGENT_MOB_PHYSICS_STUCK_DETECT_MS;
    public int AGENT_MOB_PHYSICS_STUCK_RETREAT_CHANCE_PERCENT;
    public int AGENT_MOB_PHYSICS_KNOCKBACK_PERCENT;
    public int AGENT_MOB_PHYSICS_FLINCH_RECOVERY_MS;
    public int AGENT_MOB_PHYSICS_POST_FLINCH_CHASE_RAMP_MS;
    public boolean AGENT_MOB_PHYSICS_HIT1_ENABLED;
    public int AGENT_MOB_PHYSICS_IMPACT_DELAY_PERCENT;
    public int AGENT_MOB_PHYSICS_IMPACT_DELAY_OFFSET_MS;
    public boolean AGENT_MOB_PHYSICS_DIAGNOSTIC_LOGGING;
    public boolean AGENT_MOB_PHYSICS_VIRTUAL_OBSERVER_STRESS;
    public boolean AGENT_MAP_TRANSITION_PACKET_DIAGNOSTICS;
    public int AGENT_DEATH_RESPAWN_DELAY_MS;
    public int AGENT_DEATH_RESPAWN_HP_PERCENT;
    public int AGENT_MOB_PHYSICS_OBSERVER_WARMUP_MS;
    public int AGENT_MOB_PHYSICS_AGGRO_TIMEOUT_MS;
    public boolean AGENT_LEGACY_DIALOGUE_ENABLED;
    public boolean AGENT_AMHERST_DEBUG_MESSAGES_ENABLED;
    public boolean AGENT_AMHERST_INTENTION_CHAT_ENABLED;
    public boolean AGENT_VICTORIA_INTENTION_CHAT_ENABLED;
    public boolean AGENT_AMHERST_SHOWCASE_ENABLED;
    public String AGENT_AMHERST_SHOWCASE_AGENT_NAME;
    public boolean AGENT_MAPLE_ISLAND_SHOWCASE_ENABLED;
    public String AGENT_MAPLE_ISLAND_SHOWCASE_AGENT_NAME;
    public boolean AGENT_MAPLE_ISLAND_COHORT_ENABLED;
    public boolean AGENT_PERSONALITY_PRESENTATION_ENABLED;
    public boolean AGENT_COMBAT_BEHAVIOR_ENABLED;
    public boolean AGENT_RESPONSE_LATENCY_ENABLED;
    public boolean AGENT_MAP_CROWD_RESPITE_ENABLED;
    public boolean AGENT_TARGET_CLAIM_POLICY_ENABLED;
    public boolean AGENT_TARGET_VARIATION_ENABLED;
    public boolean AGENT_PLATFORM_ANCHOR_BEHAVIOR_ENABLED;
    public boolean AGENT_NAVIGATION_BEHAVIOR_ENABLED;
    public boolean AGENT_IDLE_COMBAT_PRESENTATION_ENABLED;
    public boolean AGENT_COMBAT_EMOTES_ENABLED;
    public int AGENT_MAP_MAX_ACTIVE_COMBAT_PERCENT;
    public int AGENT_MAP_CROWD_MIN_AGENTS;
    public int AGENT_COMBAT_EMOTE_MAP_BUDGET_PER_10S;
    public int AGENT_MAPLE_ISLAND_FULL_PLATFORM_ANCHOR_PERCENT;
    public int AGENT_MAPLE_ISLAND_FULL_MIDDLE_TARGET_PERCENT;
    public int AGENT_MAPLE_ISLAND_FULL_TARGET_SHORTLIST_LIMIT;
    public int AGENT_MAPLE_ISLAND_COHORT_MAX_TOTAL;
    public int AGENT_MAPLE_ISLAND_COHORT_STALL_TIMEOUT_MS;
    public int AGENT_MAPLE_ISLAND_COHORT_TELEMETRY_RETAINED_RUNS;
    public int AGENT_MAPLE_ISLAND_COHORT_OBJECTIVE_TIMEOUT_MS;
    public int AGENT_OBJECTIVE_NUDGE_MS;
    public int AGENT_OBJECTIVE_STALL_RECOVERY_MS;
    public int AGENT_OBJECTIVE_AUTO_RECOVERY_ATTEMPTS;
    public int AGENT_OBJECTIVE_RECOVERY_DELAY_MS;
    public boolean AGENT_SOUTHPERRY_SHOWCASE_ENABLED;
    public String AGENT_SOUTHPERRY_SHOWCASE_AGENT_NAME;
    public String AGENT_AUTHORITY_ADMINISTRATOR_NAMES;
    public String AGENT_AUTHORITY_OPERATOR_NAMES;
    public String AGENT_AUTHORITY_OBSERVER_NAMES;
    public String AGENT_TRUSTED_TRADE_PLAYER_NAMES;
    public boolean AGENT_LEGACY_OWNER_COMPATIBILITY_ENABLED;
}
