package server.agents.economy.activity;

import java.time.Instant;
import java.util.Map;

/** One observed autonomous gameplay session; never generated by the simulator. */
public record ActivityCalibrationSample(String sampleId, int agentCharacterId, String agentBuild,
                                        int mapId, int level, String jobFamily, Instant startedAt,
                                        Instant completedAt, Map<Integer, Integer> killCounts,
                                        Map<Integer, Integer> consumedItems, boolean died) {
    public ActivityCalibrationSample {
        if (sampleId == null || sampleId.isBlank() || agentCharacterId <= 0 || agentBuild == null
                || mapId <= 0 || level <= 0 || jobFamily == null || startedAt == null
                || completedAt == null || !completedAt.isAfter(startedAt)) throw new IllegalArgumentException();
        killCounts = Map.copyOf(killCounts);
        consumedItems = Map.copyOf(consumedItems);
    }
}
